config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "pages#index"

  resources :games, only: [:show, :create] do
    post :start, on: :member
    post :action, on: :member
    post :end_turn, on: :member
  end

  resources :players, only: [:create]
end

app/models/action.rb
class Action
  REVEAL_LOWEST = "reveal_lowest"
  REVEAL_HIGHEST = "reveal_highest"
  REVEAL_ON_TABLE = "reveal_on_table"

  def initialize(type:, entity_id:)
    @type = type
    @entity_id = entity_id
  end

  def apply
    entity.reveal
  end

  private

  def entity
    @entity ||=
      case @type
      when REVEAL_LOWEST
        Player.find(@entity_id).lowest_card
      when REVEAL_HIGHEST
        Player.find(@entity_id).highest_card
      when REVEAL_ON_TABLE
        Card.find(@entity_id)
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  HIDDEN_VALUE = "Reveal"

  belongs_to :player, optional: true
  belongs_to :game

  scope :on_table, -> { where(player_id: nil) }
  scope :sorted, -> { order(value: :asc).in_play }
  scope :revealed, -> { where(state: :revealed) }
  scope :revealed_or_playable_by, ->(player_id) { revealed.or(playable_by(player_id)).in_play }
  scope :playable_by, ->(player_id) { owned_by(player_id).where(value: [min_for(player_id), max_for(player_id)]) }
  scope :min_for, ->(player_id) { owned_by(player_id).pluck(:value).min }
  scope :max_for, ->(player_id) { owned_by(player_id).pluck(:value).max }
  scope :owned_by, ->(player_id) { where(player_id: player_id) }
  scope :in_play, -> { where.not(state: :won) }

  enum state: {
    hidden: 0,
    revealed: 1,
    won: 2
  }

  def display_value
    return value if revealed?
    return "Won #{value}" if won?
    HIDDEN_VALUE
  end

  def reveal
    update(state: :revealed)
  end

  def hide
    update(state: :hidden)
  end

  def win
    update(state: :won)
  end
end

app/models/deck.rb
class Deck < Array
  VALUES = (1..12).to_a
  CARDS_PER_VALUE = 3

  def initialize
    super((VALUES * CARDS_PER_VALUE).shuffle)
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players, dependent: :delete_all
  has_many :cards, dependent: :delete_all

  enum state: {
    in_setup: 0,
    in_progress: 1,
    ended: 2
  }

  CARDS_PER_PLAYER_BY_COUNT = {
    3 => 9,
    4 => 7,
    5 => 6,
    6 => 5
  }

  def start
    ActiveRecord::Base.transaction do
      mark_in_progress
      deal_cards
      assign_first_user_turn
    end
  end

  def end_turn(current_player)
    ActiveRecord::Base.transaction do
      claim_trios_and_hide_mismatches(current_player)
      assign_next_player_turn
    end
  end

  def mismatch?(current_player)
    cards.revealed.pluck(:value).uniq.length > 1
  end

  def trio?(current_player)
    cards.revealed_or_playable_by(current_player.id).group_by(&:value).any? do |_, group|
      group.length == 3
    end
  end

  def reset!
    cards.map(&:hide)
  end

  private

  def claim_trios_and_hide_mismatches(current_player)
    cards.revealed_or_playable_by(current_player.id).group_by(&:value).each do |value, group|
      if group.length == 3
        group.map(&:win)
        current_player.scored
      else
        group.map(&:hide)
      end
    end
  end

  def revealed_cards
    cards.revealed
  end

  def mark_in_progress
    update(state: :in_progress)
  end

  def deal_cards
    deck = Deck.new

    players.each do |player|
      player.cards = deck.pop(CARDS_PER_PLAYER_BY_COUNT[players.count]).map do |value|
        Card.new(value: value, player: player, game: self)
      end
    end

    cards_on_table = deck.map do |value|
      Card.new(value: value, player: nil, game: self)
    end

    players.each(&:save)
    cards_on_table.map(&:save)
  end

  def assign_first_user_turn
    players.in_order.first.start_turn
  end

  def assign_next_player_turn
    active_turn_player = players.active_turn.first
    active_turn_player.end_turn

    if (active_turn_player == players.in_order.last)
      assign_first_user_turn
    else
      players.in_order[players.find_index(active_turn_player) + 1].start_turn
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
  has_many :cards

  scope :in_order, -> { order(id: :asc) }
  scope :active_turn, -> { where(active_turn: true) }

  def scored
    update(score: score + 1)
  end

  def start_turn
    update(active_turn: true)
  end

  def end_turn
    update(active_turn: false)
  end

  def sorted_cards
    cards.sorted
  end

  def lowest_card
    sorted_cards.first
  end

  def highest_card
    sorted_cards.last
  end

  def has_card?(value)
    cards.pluck(:value).include?(value)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_game_and_player

  def set_current_game_and_player
    @current_game = Game.includes(:players).find_by(id: session[:game_id])
    @current_player = Player.includes(:cards).find_by(id: session[:player_id])
  end

  def join_game(game_id, player_id)
    session[:game_id] = game_id
    session[:player_id] = player_id
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def create
    game = Game.create!
    player = game.players.create!(params.require(:player).permit(:name))
    join_game(game.id, player.id)
    redirect_to game_path(game)
  end

  def start
    game = Game.find(params[:id])
    game.start
    redirect_to game_path(game)
  end

  def action
    game = Game.find(params[:id])
    action = Action.new(
      type: params[:action_type],
      entity_id: params[:action_entity_id]
    )
    action.apply
    redirect_to game_path(game)
  end

  def end_turn
    game = Game.find(params[:id])
    game.end_turn(@current_player)
    redirect_to game_path(game)
  end

  def show
    @game = Game.includes(:players).find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @new_game = Game.new
    @new_player = Player.new
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def create
    game = Game.find(player_create_params[:game_id])
    player = game.players.create(player_create_params)
    join_game(game.id, player.id)
    redirect_to game_path(game)
  end

  private

  def player_create_params
    params.require(:player).permit(:name, :game_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/show.html.erb
<% if @game.in_setup? %>
  <%= button_to "Start Game", start_game_path(@game) %>
<% end %>

<% if @game.in_setup? || @game.in_progress? %>
  <script type="text/javascript">
    setInterval(() => window.location.reload(), 5000);
  </script>

  <div style="width:100%;box-sizing:border-box;padding:50px;text-align:center;background-color:#ccc;">
    <% if @game.mismatch?(@current_player) %>
      <%= button_to "End Turn", end_turn_game_path(@game) %>
    <% elsif @game.trio?(@current_player) %>
      trioooo
      <%= button_to "End Turn", end_turn_game_path(@game) %>
    <% end %>
  </div>

  <div style="width:100%;box-sizing:border-box;padding:50px;text-align:center;background-color:#ccc;">
    <p><strong>Cards on Table</strong></p>
    <% @game.cards.on_table.each do |card| %>
      <%= button_to card.display_value, action_game_path(@game), params: { action_type: Action::REVEAL_ON_TABLE, action_entity_id: card.id } %>
    <% end %>
  </div>

  <% colors = %w[eee efe eef fee] %>
  <div style="width:100%;display:flex;flex-wrap:wrap;">
    <% @game.players.each_with_index do |player, idx| %>
      <div style="width:25%;background-color:#<%= colors[idx] %>;box-sizing:border-box;padding:50px;text-align:center;">
        <% if player == @current_player %>
          <p><strong>This Is You</strong></p>
          <% if @current_player.active_turn? %>
            <p><strong>It's Your Turn</strong></p>
          <% end %>
        <% end %>

        <%= player.name %> (score: <%= player.score %>)

        <hr>

        <% if player == @current_player %>
          <p><strong>Your Cards</strong></p>
          <p><%= @current_player.sorted_cards.pluck(:value).join(", ") %></p>
        <% end %>

        <% if player != @current_player %>
          <%= button_to "Show Lowest Card", action_game_path(@game), params: { action_type: Action::REVEAL_LOWEST, action_entity_id: player.id } %>
          <%= button_to "Show Highest Card", action_game_path(@game), params: { action_type: Action::REVEAL_HIGHEST, action_entity_id: player.id } %>
        <% end %>

        <% if player.cards.revealed.any? %>
          <p><strong>Revealed Cards</strong></p>
          <p><%= player.cards.revealed.pluck(:value).join(", ") %></p>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<%= form_for @new_game do |f| %>
  <%= text_field_tag "player[name]", nil, placeholder: "Player Name", required: true %>
  <%= f.submit "Start New Game" %>
<% end %>

<%= form_for @new_player do |f| %>
  <%= f.number_field :game_id, placeholder: "Game ID", required: true %>
  <%= f.text_field :name, placeholder: "Player Name", required: true %>
  <%= f.submit "Join Game" %>
<% end %>